### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by HyGlobalHD** [YaBoiBalAnce/Pets#2]
Maybe U Should Use Bat Instead of Chicken.(lol)

Particle When Summon Pet

Remove some minor bug like when player remove the pet ,the pet disappear but the pet were like lagging moving like shit and sometimes the pet were have 2 when u do pets

**Comment by Adam1609** [comment]
Because this plugin doesn't have any command to change pets entites

**Comment by Vietnamese02** [comment]
how to use it ?

**Comment by HyGlobalHD** [comment]
available commands:
/pets - to toggle pets like on and off switch
/pets name (name) - Add Name To Your Pets

**Comment by Vietnamese02** [comment]
I / pets is it the chicken - how the other children

**Comment by Vietnamese02** [comment]
I use php 7

**Comment by HyGlobalHD** [comment]
Theres only 1 pets its chicken if u want others pet u should edit the plugin..

**Comment by Vietnamese02** [comment]
```
        I want to have one pig
```

**Comment by YaBoiBalAnce** [comment]
Added multiple pets and the ability to choose aswell permission based!
