### ISSUE TITLE
More?

### ISSUE THREAD

**Issue by tamaskis99** [YaBoiBalAnce/Pets#3]
Adding more animals, mobs, npc, and whitch? All adding is making the best pet plugin, AND perm to pet (ex.: pets.command.chicken for ChickenPet)?

**Comment by Vietnamese02** [comment]
Good idea

**Comment by YaBoiBalAnce** [comment]
Yes im working on adding more pets. Aswell as permission require for each pet

**Comment by tamaskis99** [comment]
Okey, I'm waiting to big update. :)

**Comment by YaBoiBalAnce** [comment]
Yea just having trouble choosing pets

**Comment by YaBoiBalAnce** [comment]
UPDATE OUT!
