### ISSUE TITLE
NETWORK_ID = ?????

### ISSUE THREAD

**Issue by Vietnamese02** [YaBoiBalAnce/Pets#7]
NETWORK_ID = ? ID and ID obtained where the little rabbit and villager? Save me fold

**Comment by Vietnamese02** [comment]
usage rights for pureperm

**Comment by Vietnamese02** [comment]
Please give me an example

**Comment by Adam1609** [comment]
You spam a lot! Maybe you can go check a resolution and make a pull request

**Comment by YaBoiBalAnce** [comment]
Its on MCPE wiki
